services:

  postgres:
    image: postgres:17
    container_name: tattoo-supply-manager-postgres
    restart: always
    environment:
      POSTGRES_DB: tattoo-supply-manager-db
      POSTGRES_USER: tattoo_user
      POSTGRES_PASSWORD: tattoo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tattoo_user -d tattoo-supply-manager-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tattoo-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Injeta no application.yml a URL apontando para o container "postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tattoo-supply-manager-db
      SPRING_DATASOURCE_USERNAME: tattoo_user
      SPRING_DATASOURCE_PASSWORD: tattoo_pass
      JWT_SECRET: local-dev-jwt-secret-troque-em-producao-32chars+

  prometheus:
    image: prom/prometheus:latest
    container_name: tattoo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: tattoo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data: